version: '3'
services:
  api:
    build:
      context: ./Api-Angular
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Api-Angular:/app
      - ./Api-Angular/db.sqlite3:/app/db.sqlite3
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=djangular.settings

  chat:
    build:
      context: ./Chat-Django
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Chat-Django:/app
      - ./Chat-Django/db.sqlite3:/app/db.sqlite3
    ports:
      - 8001:8000
    environment:
      - DJANGO_SETTINGS_MODULE=ChatProject.settings

  angular:
    build:
      context: ./Consultas_Ang
      dockerfile: Dockerfile
    ports:
      - 4200:4200
